[profile.default]
src = 'src'
out = 'out'
libs = ['lib']


[profile.default.optimizer_details]
constantOptimizer = true
yul = false
[profile.yul.optimizer] 
enabled = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/config